# Generated by Django 4.1.2 on 2022-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('banner', models.ImageField(null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timeTaken', models.CharField(max_length=50)),
                ('parag1', models.TextField()),
                ('parag2', models.TextField(blank=True, null=True)),
                ('parag3', models.TextField(blank=True, null=True)),
                ('parag4', models.TextField(blank=True, null=True)),
                ('qoute', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author_details', models.TextField(blank=True, null=True)),
                ('author_instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('author_facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('author_twitter', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sm_image_x1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x2', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x4', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x5', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x6', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x7', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('tag_slug', models.SlugField(blank=True)),
                ('category', models.CharField(max_length=200)),
                ('cat_slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=50)),
                ('previous_price', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, choices=[('m', 'Men'), ('w', 'Women'), ('k', 'Kids')], default='m', help_text='Product tags', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('j', 'Just In'), ('o', 'Out of Stock')], default='a', help_text='Product status', max_length=1)),
            ],
        ),
    ]
