# Generated by Django 4.1.2 on 2023-01-14 21:12

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('banner', models.ImageField(null=True, upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timeTaken', models.CharField(max_length=50)),
                ('parag1', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('parag2', models.TextField(blank=True, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('qoute', models.TextField(blank=True, null=True)),
                ('parag3', models.TextField(blank=True, null=True)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('parag4', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author_details', models.TextField(blank=True, null=True)),
                ('author_instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('author_facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('author_twitter', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sm_image_x1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x2', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x4', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x5', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x6', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image_x7', models.ImageField(blank=True, null=True, upload_to='')),
                ('sm_image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('tag_slug', models.SlugField(blank=True)),
                ('category', models.CharField(max_length=200)),
                ('cat_slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pro_slug', models.SlugField(blank=True)),
                ('price', models.CharField(max_length=50)),
                ('previous_price', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, choices=[('m', 'Men'), ('w', 'Women'), ('k', 'Kids')], default='m', help_text='Product tags', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('j', 'Just In'), ('o', 'Out of Stock')], default='a', help_text='Product status', max_length=1)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('shopping_preference', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', base.models.UserManager()),
            ],
        ),
    ]
