# Generated by Django 4.1.2 on 2023-01-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='date_of_birth',
        ),
    ]
