# Generated by Django 4.1.2 on 2023-01-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_date_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
