# Generated by Django 4.1.2 on 2022-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_author_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
