# Generated by Django 4.1.2 on 2023-01-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_article_options_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='timeTaken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
