# Generated by Django 4.1.2 on 2022-12-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_sm_image_x1_product_sm_image_x2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
