# Generated by Django 4.1.2 on 2022-12-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
